package edu.uniquindio.dentalmanagementsystembackend.Enum;

public enum TipoProducto {
    MATERIAL_DESECHABLE,
    INSTRUMENTAL_QUIRURGICO,
    FARMACO,
    EQUIPO_MEDICO,
    MATERIAL_RADIOLOGICO,
    MATERIAL_ORTODONCICO,
    MATERIAL_PROTESICO,
    MATERIAL_ENDODONCICO,
    PRODUCTO_LIMPIEZA,
    CONSUMIBLE_ADMINISTRATIVO
}